"""empty message

Revision ID: 15b8f53a884f
Revises: 1518b6b5a22d
Create Date: 2023-07-06 11:49:10.320114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15b8f53a884f'
down_revision = '1518b6b5a22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('edited')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('created',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
