"""empty message

Revision ID: 58b5892a3d44
Revises: 15b8f53a884f
Create Date: 2023-07-06 11:50:02.697267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b5892a3d44'
down_revision = '15b8f53a884f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
