"""empty message

Revision ID: 6b0986837718
Revises: ebeb6c847dde
Create Date: 2023-07-05 10:12:29.475602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0986837718'
down_revision = 'ebeb6c847dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Passengers')
    op.drop_table('Pilots')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.create_table('Pilots',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Pilots_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pilot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['character.id'], name='Pilots_pilot_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='Pilots_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Pilots_pkey')
    )
    op.create_table('Passengers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Passengers_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passenger_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['character.id'], name='Passengers_passenger_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='Passengers_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Passengers_pkey')
    )
    op.drop_table('pilots')
    op.drop_table('passengers')
    # ### end Alembic commands ###
