"""empty message

Revision ID: aba27ea936c7
Revises: 6b0986837718
Create Date: 2023-07-06 11:42:13.187216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aba27ea936c7'
down_revision = '6b0986837718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pilots')
    op.drop_table('passengers')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('edited')
        batch_op.drop_column('created')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('terrain')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('passengers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='passengers_character_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='passengers_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='passengers_pkey')
    )
    op.create_table('pilots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='pilots_character_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='pilots_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pilots_pkey')
    )
    op.drop_table('favorite_vehicles')
    op.drop_table('favorite_planets')
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###
